### ISSUE TITLE
#include <../ZKRTypes.h>

### ISSUE THREAD

**Issue by sv1onw** [clytras/TM1637Display#1]
Hello Chris,

It seems that I cannot locate the header : #include <../ZKRTypes.h>
I am trying to run the UVScanner software.
Your TM1637 Cpp file seems modified at this point from the original lib.
Am I missing something?
Thanks,
Konstantinos

**Comment by clytras** [comment]
Γεια σου Κωνσταντίνε!

Nice catch! That's my bad! I forgot to include that file because it’s a directory up from the library to have other projects use it from a global scope. I have now commited the file and a minor change to include it properly from the current library directory. Thanks for reporting this!

Contact me if you need any help with your project.

**Comment by sv1onw** [comment]
Yhanks a lot Chris.
Cheers
